/*
 * Entity Containment API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	entitycontainment "github.com/rtk-logan-fillo/entity-containment-mvp/entity-containment"
)

func main() {
	log.Printf("Server started")

	ContainmentApiService := entitycontainment.NewContainmentApiService()
	ContainmentApiController := entitycontainment.NewContainmentApiController(ContainmentApiService)

	router := entitycontainment.NewRouter(ContainmentApiController)

	log.Fatal(http.ListenAndServe(":1234", router))
}
