/*
 * Entity Containment API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package entitycontainment

import (
	"context"
	"net/http"
)

// ContainmentApiRouter defines the required methods for binding the api requests to a responses for the ContainmentApi
// The ContainmentApiRouter implementation should parse necessary information from the http request,
// pass the data to a ContainmentApiServicer to perform the required actions, then write the service results to the http response.
type ContainmentApiRouter interface {
	BulkLookupContainmentStatus(http.ResponseWriter, *http.Request)
	HealthCheck(http.ResponseWriter, *http.Request)
	LookupIsContainmentActive(http.ResponseWriter, *http.Request)
	RequestContainment(http.ResponseWriter, *http.Request)
	RequestLiftContainment(http.ResponseWriter, *http.Request)
}

// ContainmentApiServicer defines the api actions for the ContainmentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ContainmentApiServicer interface {
	BulkLookupContainmentStatus(context.Context, string, string, DeviceIdList) (ImplResponse, error)
	HealthCheck(context.Context) (ImplResponse, error)
	LookupIsContainmentActive(context.Context, string, string) (ImplResponse, error)
	RequestContainment(context.Context, string, string, string) (ImplResponse, error)
	RequestLiftContainment(context.Context, string, string, string) (ImplResponse, error)
}
