/*
 * Entity Containment API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package entitycontainment

type GenericErrorResponseErrorsInner struct {
	Code int32 `json:"code,omitempty"`

	Field string `json:"field,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertGenericErrorResponseErrorsInnerRequired checks if the required fields are not zero-ed
func AssertGenericErrorResponseErrorsInnerRequired(obj GenericErrorResponseErrorsInner) error {
	return nil
}

// AssertRecurseGenericErrorResponseErrorsInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GenericErrorResponseErrorsInner (e.g. [][]GenericErrorResponseErrorsInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGenericErrorResponseErrorsInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGenericErrorResponseErrorsInner, ok := obj.(GenericErrorResponseErrorsInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGenericErrorResponseErrorsInnerRequired(aGenericErrorResponseErrorsInner)
	})
}
